#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

[[ $(git rev-parse --abbrev-ref HEAD) =~ ^(main|dev) ]] \
&& \
    echo "Building unit tests..."
    ./Tests/build.bat

    ./Tests/Win32/Release/UnitTests.exe -b -cm:Quiet -l:Error \
|| echo "Not on a branch where unit tests are required"
